Update patch set 5
Patch Set 5:

After looking at the rpmbuild log and consulting jpena, it seems that the issue is as follows:

OSError: [Errno 16] Device or resource busy: '/var/lib/mock/delorean-centos7-x86_64/root/var/cache/yum'

It seems that some previous build got stuck and was aborted and it'd be required to unmount /var/lib/mock/delorean-centos7-x86_64/root/var/cache/yum locally.

Can someone with the proper rights take care of it?

Thanks!

Patch-set: 5